apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "user_db"
  DB_USERNAME: "root"
  DB_TYPE: "mysql"