apiVersion: v1
kind: Service
metadata:
  name: product-microservice
spec:
  type: ClusterIP
  selector:
    app: product-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003