apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: myacr.azurecr.io/auth-microservice:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
      imagePullSecrets:
        - name: acr-secret