apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"   # Uses system-assigned identity
    userAssignedIdentityID: ""     # Leave empty if not using user-assigned
    keyvaultName: "your-keyvault-name"
    cloudName: ""
    objects:
      - |
        objectName: DB_PASSWORD
        objectType: secret
        objectVersion: ""
      - |
        objectName: JWT_SECRET
        objectType: secret
        objectVersion: ""
    resourceGroup: "your-resource-group"
    subscriptionId: "your-subscription-id"
    tenantId: "your-tenant-id"