apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "myKeyVault369"
    cloudName: ""
    objects: |
      - objectName: DB-PASSWORD
        objectType: secret
        objectVersion: ""
      - objectName: JWT-SECRET
        objectType: secret
        objectVersion: ""
    resourceGroup: "myResourceGroup"
    subscriptionId: "7091c019-9e61-4539-8f5c-2f6c4e91ebb8"
    tenantId: "191a8b77-0700-47c8-a5e5-747fdb56d0a5"